uploads = []
generated = []

[[outputs]]
id = "mDg-7ZbQ50viysgozAczC"
uri = "file://screenshots/play_home.jpg"
type = "image"
title = "Home Screen"

[[outputs]]
id = "IgzqK-NnYFOjhceJE7JVf"
uri = "file://screenshots/play_library.jpg"
type = "image"
title = "Library Screen"

[[outputs]]
id = "rG1N2cW4gkZ_4WRyUNzjr"
uri = "file://screenshots/play_settings_v2.jpg"
type = "image"
title = "Settings Screen (v1.7.0)"

[[outputs]]
id = "WKyfAcyLlrwOCe5M4bv3S"
uri = "file://screenshots/play_tutorial.jpg"
type = "image"
title = "Onboarding / Tutorial"

[[outputs]]
id = "0KuMj_58QI2KIbtgKi-WU"
uri = "file://screenshots/marketing/01_home.jpg"
type = "image"
title = "01 — Home (All your videos. Beautifully organized.)"

[[outputs]]
id = "2PPXHvF_5df8fClbpM3ek"
uri = "file://screenshots/marketing/02_library.jpg"
type = "image"
title = "02 — Library (Sort your way. Your rules.)"

[[outputs]]
id = "c-jTeE6_RUCcq7yTy6GJo"
uri = "file://screenshots/marketing/03_features.jpg"
type = "image"
title = "03 — Features (Powerful features. Zero compromise.)"

[[outputs]]
id = "OI4kvDW-vxROWdpHumL5h"
uri = "file://screenshots/marketing/04_tutorial.jpg"
type = "image"
title = "04 — Onboarding (Up and running in seconds.)"

[[outputs]]
id = "rVYDCxXI8cGL4kOtVUBSl"
uri = "file://screenshots/marketing/banner_1024.jpg"
type = "image"
title = "Play — 1024×1024 Banner"

[[outputs]]
id = "w3009y80xZ7oJ5e63GDco"
uri = "file://screenshots/marketing/icon_512.jpg"
type = "image"
title = "App Icon — 512×512"

[[outputs]]
id = "RqiN5eehFk526TRF_PGqW"
uri = "file://screenshots/marketing/feature_graphic_1024x500.jpg"
type = "image"
title = "Feature Graphic — 1024×500"
